jobs:
- name: u16scaall-test
  type: runSh
  steps:
    - TASK:
        runtime:
          options:
            imageName: "drydock/u16scaall"
            imageTag: master
        script:
            - /usr/local/scala-2.12.6/bin/scala -version
            - /usr/local/scala-2.11.12/bin/scala -version
